version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
        depends_on:
            - app

    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        depends_on:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=DB_SECRET"
            - "MYSQL_DATABASE=DB_NAME"
        ports:
            - 3306

    cache:
        image: redis:3.0
        ports:
            - 6379
